-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSL0VElEuc7JuqIni
98MAaH+1vpHfQfYJyJNBZTGCzjigCgYIKoZIzj0DAQehRANCAATBy3Uq8cGQ0bWo
pmvaI7s9m9+x1qtc7/DJJRcMp3A7QUVU0BaoNpg9L6F0UNOp+8qiQGYkwcMnlVzl
ApXbxmbO
-----END PRIVATE KEY-----